name-template: v$NEXT_PATCH_VERSION 🌈
tag-template: v$NEXT_PATCH_VERSION
no-changes-template: No Changes
branches:
  - master
categories:
  - title: 🚀 Features
    label: feat
  - title: 🐛 Bug Fixes
    label: fix
  - title: 🔨 Maintenance
    label: chore
  - title: 📖 Documentation
    label: docs
  - title: 📦 Dependency updates
    label: dependencies
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## Changelog

  $CHANGES

  A big thanks to:

  $CONTRIBUTORS
