sudo: false
language: java
jdk:
  - openjdk8
before_script:
  - echo "before_script"
cache:
  directories:
  - $HOME/.m2
install: true
script:
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
